//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class demands
    {
        public int Id { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public string Address_House { get; set; }
        public string Address_Number { get; set; }
        public Nullable<int> MinPrice { get; set; }
        public Nullable<int> MaxPrice { get; set; }
        public int AgentId { get; set; }
        public int ClientId { get; set; }
        public string MinArea { get; set; }
        public string MaxArea { get; set; }
        public string MinRooms { get; set; }
        public string MaxRooms { get; set; }
        public string MinFloor { get; set; }
        public string MaxFloor { get; set; }
        public int TypeId { get; set; }
    
        public virtual agents agents { get; set; }
        public virtual clients clients { get; set; }
        public virtual typeProperty typeProperty { get; set; }
    }
}
