//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplies
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public int AgentId { get; set; }
        public int ClientId { get; set; }
        public int RealEstateId { get; set; }
    
        public virtual agents agents { get; set; }
        public virtual clients clients { get; set; }
        public virtual property property { get; set; }
    }
}
